/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewBotRouteImport } from './routes/review-bot'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as HistoryRunIdRouteImport } from './routes/history_.$runId'
import { Route as ApiInngestRouteImport } from './routes/api.inngest'

const ReviewBotRoute = ReviewBotRouteImport.update({
  id: '/review-bot',
  path: '/review-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRunIdRoute = HistoryRunIdRouteImport.update({
  id: '/history_/$runId',
  path: '/history/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/history_/$runId': typeof HistoryRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credentials'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/history/$runId'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credentials'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/history/$runId'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/credentials'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/history_/$runId'
    | '/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CredentialsRoute: typeof CredentialsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  ReviewBotRoute: typeof ReviewBotRoute
  ApiInngestRoute: typeof ApiInngestRoute
  HistoryRunIdRoute: typeof HistoryRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-bot': {
      id: '/review-bot'
      path: '/review-bot'
      fullPath: '/review-bot'
      preLoaderRoute: typeof ReviewBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$runId': {
      id: '/history_/$runId'
      path: '/history/$runId'
      fullPath: '/history/$runId'
      preLoaderRoute: typeof HistoryRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CredentialsRoute: CredentialsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  ReviewBotRoute: ReviewBotRoute,
  ApiInngestRoute: ApiInngestRoute,
  HistoryRunIdRoute: HistoryRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
