/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewBotRouteImport } from './routes/review-bot'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiGithubInstallCallbackRouteImport } from './routes/api/github/install/callback'

const ReviewBotRoute = ReviewBotRouteImport.update({
  id: '/review-bot',
  path: '/review-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallCallbackRoute =
  ApiGithubInstallCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiGithubInstallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/runs/$runId'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/github/install/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/runs/$runId'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/github/install/callback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/runs/$runId'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/github/install/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  ReviewBotRoute: typeof ReviewBotRoute
  ApiInngestRoute: typeof ApiInngestRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRouteWithChildren
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-bot': {
      id: '/review-bot'
      path: '/review-bot'
      fullPath: '/review-bot'
      preLoaderRoute: typeof ReviewBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/callback': {
      id: '/api/github/install/callback'
      path: '/callback'
      fullPath: '/api/github/install/callback'
      preLoaderRoute: typeof ApiGithubInstallCallbackRouteImport
      parentRoute: typeof ApiGithubInstallRoute
    }
  }
}

interface ApiGithubInstallRouteChildren {
  ApiGithubInstallCallbackRoute: typeof ApiGithubInstallCallbackRoute
}

const ApiGithubInstallRouteChildren: ApiGithubInstallRouteChildren = {
  ApiGithubInstallCallbackRoute: ApiGithubInstallCallbackRoute,
}

const ApiGithubInstallRouteWithChildren =
  ApiGithubInstallRoute._addFileChildren(ApiGithubInstallRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  ReviewBotRoute: ReviewBotRoute,
  ApiInngestRoute: ApiInngestRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubInstallRoute: ApiGithubInstallRouteWithChildren,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
