/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewBotRouteImport } from './routes/review-bot'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as BackgroundAgentsRouteImport } from './routes/background-agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as ReportRunIdRouteImport } from './routes/report.$runId'
import { Route as HistoryRunIdRouteImport } from './routes/history_.$runId'
import { Route as BackgroundAgentsOrchestratorIdRouteImport } from './routes/background-agents.$orchestratorId'
import { Route as ApiInngestRouteImport } from './routes/api.inngest'
import { Route as ApiLocalHelperActionRouteImport } from './routes/api.local-helper.$action'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiSteelSessionIdMediaRouteImport } from './routes/api.steel.$sessionId.media'
import { Route as ApiSteelSessionIdHlsRouteImport } from './routes/api.steel.$sessionId.hls'
import { Route as ApiGithubInstallCallbackRouteImport } from './routes/api/github/install/callback'

const ReviewBotRoute = ReviewBotRouteImport.update({
  id: '/review-bot',
  path: '/review-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundAgentsRoute = BackgroundAgentsRouteImport.update({
  id: '/background-agents',
  path: '/background-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRunIdRoute = ReportRunIdRouteImport.update({
  id: '/report/$runId',
  path: '/report/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRunIdRoute = HistoryRunIdRouteImport.update({
  id: '/history_/$runId',
  path: '/history/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundAgentsOrchestratorIdRoute =
  BackgroundAgentsOrchestratorIdRouteImport.update({
    id: '/$orchestratorId',
    path: '/$orchestratorId',
    getParentRoute: () => BackgroundAgentsRoute,
  } as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalHelperActionRoute = ApiLocalHelperActionRouteImport.update({
  id: '/api/local-helper/$action',
  path: '/api/local-helper/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteelSessionIdMediaRoute = ApiSteelSessionIdMediaRouteImport.update({
  id: '/api/steel/$sessionId/media',
  path: '/api/steel/$sessionId/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteelSessionIdHlsRoute = ApiSteelSessionIdHlsRouteImport.update({
  id: '/api/steel/$sessionId/hls',
  path: '/api/steel/$sessionId/hls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallCallbackRoute =
  ApiGithubInstallCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiGithubInstallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background-agents': typeof BackgroundAgentsRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/background-agents/$orchestratorId': typeof BackgroundAgentsOrchestratorIdRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/report/$runId': typeof ReportRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/local-helper/$action': typeof ApiLocalHelperActionRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/steel/$sessionId/hls': typeof ApiSteelSessionIdHlsRoute
  '/api/steel/$sessionId/media': typeof ApiSteelSessionIdMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background-agents': typeof BackgroundAgentsRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/background-agents/$orchestratorId': typeof BackgroundAgentsOrchestratorIdRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/report/$runId': typeof ReportRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/local-helper/$action': typeof ApiLocalHelperActionRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/steel/$sessionId/hls': typeof ApiSteelSessionIdHlsRoute
  '/api/steel/$sessionId/media': typeof ApiSteelSessionIdMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background-agents': typeof BackgroundAgentsRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/review-bot': typeof ReviewBotRoute
  '/api/inngest': typeof ApiInngestRoute
  '/background-agents/$orchestratorId': typeof BackgroundAgentsOrchestratorIdRoute
  '/history_/$runId': typeof HistoryRunIdRoute
  '/report/$runId': typeof ReportRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/local-helper/$action': typeof ApiLocalHelperActionRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/steel/$sessionId/hls': typeof ApiSteelSessionIdHlsRoute
  '/api/steel/$sessionId/media': typeof ApiSteelSessionIdMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background-agents'
    | '/credentials'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/background-agents/$orchestratorId'
    | '/history/$runId'
    | '/report/$runId'
    | '/runs/$runId'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/local-helper/$action'
    | '/api/github/install/callback'
    | '/api/steel/$sessionId/hls'
    | '/api/steel/$sessionId/media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background-agents'
    | '/credentials'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/background-agents/$orchestratorId'
    | '/history/$runId'
    | '/report/$runId'
    | '/runs/$runId'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/local-helper/$action'
    | '/api/github/install/callback'
    | '/api/steel/$sessionId/hls'
    | '/api/steel/$sessionId/media'
  id:
    | '__root__'
    | '/'
    | '/background-agents'
    | '/credentials'
    | '/dashboard'
    | '/history'
    | '/review-bot'
    | '/api/inngest'
    | '/background-agents/$orchestratorId'
    | '/history_/$runId'
    | '/report/$runId'
    | '/runs/$runId'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/local-helper/$action'
    | '/api/github/install/callback'
    | '/api/steel/$sessionId/hls'
    | '/api/steel/$sessionId/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundAgentsRoute: typeof BackgroundAgentsRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  ReviewBotRoute: typeof ReviewBotRoute
  ApiInngestRoute: typeof ApiInngestRoute
  HistoryRunIdRoute: typeof HistoryRunIdRoute
  ReportRunIdRoute: typeof ReportRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRouteWithChildren
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiLocalHelperActionRoute: typeof ApiLocalHelperActionRoute
  ApiSteelSessionIdHlsRoute: typeof ApiSteelSessionIdHlsRoute
  ApiSteelSessionIdMediaRoute: typeof ApiSteelSessionIdMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-bot': {
      id: '/review-bot'
      path: '/review-bot'
      fullPath: '/review-bot'
      preLoaderRoute: typeof ReviewBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-agents': {
      id: '/background-agents'
      path: '/background-agents'
      fullPath: '/background-agents'
      preLoaderRoute: typeof BackgroundAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$runId': {
      id: '/report/$runId'
      path: '/report/$runId'
      fullPath: '/report/$runId'
      preLoaderRoute: typeof ReportRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$runId': {
      id: '/history_/$runId'
      path: '/history/$runId'
      fullPath: '/history/$runId'
      preLoaderRoute: typeof HistoryRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-agents/$orchestratorId': {
      id: '/background-agents/$orchestratorId'
      path: '/$orchestratorId'
      fullPath: '/background-agents/$orchestratorId'
      preLoaderRoute: typeof BackgroundAgentsOrchestratorIdRouteImport
      parentRoute: typeof BackgroundAgentsRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-helper/$action': {
      id: '/api/local-helper/$action'
      path: '/api/local-helper/$action'
      fullPath: '/api/local-helper/$action'
      preLoaderRoute: typeof ApiLocalHelperActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steel/$sessionId/media': {
      id: '/api/steel/$sessionId/media'
      path: '/api/steel/$sessionId/media'
      fullPath: '/api/steel/$sessionId/media'
      preLoaderRoute: typeof ApiSteelSessionIdMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steel/$sessionId/hls': {
      id: '/api/steel/$sessionId/hls'
      path: '/api/steel/$sessionId/hls'
      fullPath: '/api/steel/$sessionId/hls'
      preLoaderRoute: typeof ApiSteelSessionIdHlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/callback': {
      id: '/api/github/install/callback'
      path: '/callback'
      fullPath: '/api/github/install/callback'
      preLoaderRoute: typeof ApiGithubInstallCallbackRouteImport
      parentRoute: typeof ApiGithubInstallRoute
    }
  }
}

interface BackgroundAgentsRouteChildren {
  BackgroundAgentsOrchestratorIdRoute: typeof BackgroundAgentsOrchestratorIdRoute
}

const BackgroundAgentsRouteChildren: BackgroundAgentsRouteChildren = {
  BackgroundAgentsOrchestratorIdRoute: BackgroundAgentsOrchestratorIdRoute,
}

const BackgroundAgentsRouteWithChildren =
  BackgroundAgentsRoute._addFileChildren(BackgroundAgentsRouteChildren)

interface ApiGithubInstallRouteChildren {
  ApiGithubInstallCallbackRoute: typeof ApiGithubInstallCallbackRoute
}

const ApiGithubInstallRouteChildren: ApiGithubInstallRouteChildren = {
  ApiGithubInstallCallbackRoute: ApiGithubInstallCallbackRoute,
}

const ApiGithubInstallRouteWithChildren =
  ApiGithubInstallRoute._addFileChildren(ApiGithubInstallRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundAgentsRoute: BackgroundAgentsRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  ReviewBotRoute: ReviewBotRoute,
  ApiInngestRoute: ApiInngestRoute,
  HistoryRunIdRoute: HistoryRunIdRoute,
  ReportRunIdRoute: ReportRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubInstallRoute: ApiGithubInstallRouteWithChildren,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiLocalHelperActionRoute: ApiLocalHelperActionRoute,
  ApiSteelSessionIdHlsRoute: ApiSteelSessionIdHlsRoute,
  ApiSteelSessionIdMediaRoute: ApiSteelSessionIdMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
